### ISSUE TITLE
Not able to access on QNAP Container Station

### ISSUE THREAD

**Issue by sw-dev1** [tuxflo/docker-mediathekview#1]
Hi,

On QNAP Container Station the install finishes and server starts according to the console, but there is no URL for accessing the container. Port 8080 is used by QNAP administration. Usually A new port is assigned automatically, but not iin this case. Extract from console:

INFO: Binding org.glyptodon.guacamole.net.basic.rest.activeconnection.ActiveConnectionRESTService to GuiceManagedComponentProvider with the scope "PerRequest"  
May 25, 2016 6:53:12 PM com.sun.jersey.spi.inject.Errors processErrorMessages  
WARNING: The following warnings have been detected with resource and/or provider classes:  
  WARNING: A sub-resource method, public void org.glyptodon.guacamole.net.basic.rest.activeconnection.ActiveConnectionRESTService.patchTunnels(java.lang.String,java.util
.List) throws org.glyptodon.guacamole.GuacamoleException, with URI template, "/", is treated as a resource method  
May 25, 2016 6:53:12 PM org.apache.jasper.EmbeddedServletOptions <init>  
SEVERE: The scratchDir you specified: /var/lib/tomcat7/work/Catalina/localhost/_ is unusable.  
May 25, 2016 6:53:12 PM org.apache.coyote.AbstractProtocol start  
INFO: Starting ProtocolHandler ["http-bio-8080"]  
May 25, 2016 6:53:12 PM org.apache.catalina.startup.Catalina start  
INFO: Server startup in 34213 ms 

Any ideas?

Thanks!

**Comment by tuxflo** [comment]
Hi!
You have to specify the port you want to use inside the advanced settings of the Container Station. 
![Advanced settings screenshot](http://www.blisshq.com/images/blog/installing-bliss-qnap-docker-container/create-container-advanced-network.png)
The port 8080 is only used inside the container, so you have map any port (for example 54321) of the NAS to the container.
According to the Screenshot above:
Replace 3321 on the Host side with the port you want to use (for example 54321) and replace the 3321 on the container side with 8080.
If you are starting the container from commandline you can use the command listed in the READE.md file replacing <PORT> with 54321.
The VNC should then be accesible by visiting http://nas_url:54321
Just let me know if you have any other questions.

**Comment by oywino** [comment]
And how do you do this if you need to use HOST mode ?

**Comment by tuxflo** [comment]
Hi @oywino 
the image is currently not built for network_mode host, because out of the box it uses port 8080, which is already in use from the QNAP GUI.
I think one can change the port, but I don't know exactly where to do that.

**Comment by oywino** [comment]
> Hi @oywino the image is currently not built for network_mode host, because out of the box it uses port 8080.

Hi @tuxflo 
I found that it can be done using docker compose;

```
    network_mode: host

    ports:
      - 49155:80
```

**Comment by tuxflo** [comment]
Usually network mode host and ports don't work together, are you sure that those lines are doing the correct port remapping?

**Comment by oywino** [comment]
What do you mean:  "are sound"  ?

**Comment by tuxflo** [comment]
Sorry, it was caused by the autocompletion of the Android keyboard. I edited the previous comment. I just asked if the code is really working that way because usually network_mode host ignores the port settings.

**Comment by oywino** [comment]
Well, the thing is that if I use:

```
 network_mode: host

    ports:
      - 49155:80
```
Then it works perfectly,  but if I use Bridge mode with Static IP, then port mapping is ignored. And I don't understand why.
